# Generated by Django 2.2.7 on 2019-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Datetime'),
        ),
    ]
