# Generated by Django 2.2.7 on 2019-12-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_service_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='car_model',
            field=models.CharField(max_length=100, verbose_name='Car model'),
        ),
    ]
