# Generated by Django 2.2.7 on 2019-12-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_service_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
